### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by htorianik** [D34DStone/pyiboard#1]
**Main tasks**
- [x] rewrite file serve system. 
_file routes should be like that:_
`/files/uploads/file.ext`
`/files/resources/file.ext`
- [x] make render of single thread like board render
- [x] make posts constructor
- [ ] add possibility to refer to yearly uploaded files 
- [ ] make modern and secure login
- [ ] the same to registration
- [ ] make a normal session management 
- [ ] implement permissions
_..._

**Extra tasks**
_..._
